extends: default

rules:
  braces:
    max-spaces-inside: 1
  comments:
    level: error
  comments-indentation:
    level: warning
  document-end:
    present: no
  document-start:
    level: error
    present: yes
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  line-length:
    level: warning
    max: 100
